### Find all content
GET http://localhost:8080/api/content

### Get content by id
GET http://localhost:8080/api/content/1

### Create new content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "Something just like this",
  "desc": "If i can't be close to you, i'll miss you more than life",
  "status": "PUBLISHED",
  "contentType": "ARTICLE",
  "dateCreated": "2024-08-20T00:50:59.715545",
  "dateUpdated": null,
  "url": "http://localhost:8080/c/2"
}

### Update content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": ";",
  "desc": "Closer",
  "status": "PUBLISHED",
  "contentType": "ARTICLE",
  "dateCreated": "2024-08-20T00:50:59.715545",
  "dateUpdated": "2024-08-20T00:50:59.715545",
  "url": "http://localhost:8080/c/3"
}

### Update content with invalid id
PUT http://localhost:8080/api/content/99
Content-Type: application/json

{
  "id": 1,
  "title": ";",
  "desc": "Closer",
  "status": "PUBLISHED",
  "contentType": "ARTICLE",
  "dateCreated": "2024-08-20T00:50:59.715545",
  "dateUpdated": "2024-08-20T00:50:59.715545",
  "url": "http://localhost:8080/c/3"
}

### Delete content with id
DELETE http://localhost:8080/api/content/1
