spring.application.name=EmployeeCRUD

# Add Database things
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
